---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: ${clusterName}
endpoint: "https://${clusterDomain}.${rootDomain}:6443"
domain: ${clusterDomain}.${rootDomain}

talosVersion: v1.6.0
kubernetesVersion: 1.29.0

cniConfig:
  name: none

additionalApiServerCertSans: &san
  - localhost
  - ${clusterEndpointIP}
  - ${clusterDomain}.${rootDomain}
additionalMachineCertSans: *san

nodes:
  - hostname: ${clusterName}-master-01
    ipAddress: 172.19.82.31
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          busPath: "0*"
        dhcp: false
        mtu: 1500
        routes: &gateway
          - network: 0.0.0.0/0
            gateway: 172.19.82.1
        addresses:
          - 172.19.82.31/24

  - hostname: ${clusterName}-master-02
    ipAddress: 172.19.82.32
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          busPath: "0*"
        dhcp: false
        mtu: 1500
        routes: *gateway
        addresses:
          - 172.19.82.32/24

  - hostname: ${clusterName}-master-03
    ipAddress: 172.19.82.33
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          busPath: "0*"
        dhcp: false
        mtu: 1500
        routes: *gateway
        addresses:
          - 172.19.82.33/24

  - hostname: ${clusterName}-worker-01
    ipAddress: 172.19.82.34
    installDisk: /dev/sda
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          busPath: "0*"
        mtu: 1500
        routes: *gateway
        addresses:
          - 172.19.82.34/24

  - hostname: ${clusterName}-worker-02
    ipAddress: 172.19.82.35
    installDisk: /dev/sda
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          busPath: "0*"
        dhcp: false
        mtu: 1500
        routes: *gateway
        addresses:
          - 172.19.82.35/24

  - hostname: ${clusterName}-worker-03
    ipAddress: 172.19.82.36
    installDisk: /dev/sda
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          busPath: "0*"
        dhcp: false
        mtu: 1500
        routes: *gateway
        addresses:
          - 172.19.82.36/24

patches:
# Disable DHCP search domain
  - |-
    machine:
      network:
        disableSearchDomain: true

# Force nameserver
  - |-
    machine:
      network:
        nameservers:
          - 172.19.82.10

# Configure NTP
  - |-
    machine:
      time:
        servers:
          - time.apple.com
          - time.cloudflare.com

# Enable KubePrism
  - |-
    machine:
      features:
        kubePrism:
          enabled: true
          port: 7445

# Configure cluster loopback
  - |-
    machine:
      network:
        extraHostEntries:
          - ip: ${clusterEndpointIP}
            aliases:
              - ${clusterDomain}.${rootDomain}

# Cluster configuration
  - |-
    cluster:
      allowSchedulingOnMasters: false
      proxy:
        disabled: true

# Cluster network configuration
## each cluster using three xx.0/20, first = node, second = pod, third = svc;
## exclude 10.10.0.0/20, 10.10.10.10 save for cluster-mesh
  - |-
    cluster:
      network:
        podSubnets:
          - 10.10.32.0/20
        serviceSubnets:
          - 10.10.48.0/20

# Kubelet configuration
  - |-
    machine:
      kubelet:
        extraArgs:
          rotate-server-certificates: "true"
        nodeIP:
          validSubnets:
            - 172.19.82.0/24

# Custom sysctls
  - |-
    machine:
      sysctls:
        fs.inotify.max_user_watches: "1048576"
        fs.inotify.max_user_instances: "8192"

# Enable DRBD
  - |-
    machine:
      kernel:
        modules:
          - name: drbd
            parameters:
              - usermode_helper=disabled
          - name: drbd_transport_tcp

# Configure containerd
## Allowing non-root containers to listen ports < 1024; Allowing ICMP on containers without any capabilities
  - |-
    machine:
      files:
        - content: |
            [plugins]
              [plugins."io.containerd.grpc.v1.cri"]
                sandbox_image = "hub.homelab.internal/k8s.io/pause:3.8"
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
          path: /etc/cri/conf.d/20-customization.part
          op: create

# Configure pull through cache, change to zot
  - |-
    machine:
      registries:
        mirrors:
          docker.io:
            endpoints:
              - http://172.19.82.10:5000
          ghcr.io:
            endpoints:
              - http://172.19.82.10:5000
          gcr.io:
            endpoints:
              - http://172.19.82.10:5000
          registry.k8s.io:
            endpoints:
              - http://172.19.82.10:5000
          quay.io:
            endpoints:
              - http://172.19.82.10:5000

controlPlane:
  schematic: &talos-image
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/drbd

  patches:
    # ETCD configuration
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 172.19.82.0/24

    # Prepare for Rook-CEPH
    - |-
      - op: replace
        path: /cluster/apiServer/admissionControl/0/configuration/exemptions/namespaces
        value:
          - kube-system
          - rook-ceph

worker:
  schematic: *talos-image
